services:
  backend:
    build:
      context: .
      dockerfile: backend/Dockerfile

    container_name: adaptive-signal-intelligence-backend

    ports:
      - "8000:8000"

    environment:
      MONGODB_URI: mongodb://mongo:27017
      MONGODB_DATABASE: adaptive_signal_intelligence

    depends_on:
      - mongo

  mongo:
    image: mongo:8

    container_name: adaptive-signal-intelligence-mongo

    ports:
      - "27017:27017"

    volumes:
      - mongo_data:/data/db

volumes:
  mongo_data: